### ISSUE TITLE
how to differentiate the different levels of the headers better within the .Rmd and resulting htlm?

### ISSUE THREAD

**Issue by janverbesselt** [GeoScripting-WUR/Scripting4GeoIntro#2]
how to use color or different styles to differentiate # or ## or ### better from each other.

**Comment by loicdtx** [comment]
You may add
number_sections: true
in the header of Rmd file

**Comment by janverbesselt** [comment]
done and is ok for now. I was thinking about the "font" size of the headers as these do not differ a lot for the other levels. This is a minor issue so not critical for now.
