### ISSUE TITLE
Use of rm/setwd

### ISSUE THREAD

**Issue by GreatEmerald** [GeoScripting-WUR/Scripting4GeoIntro#4]
The page currently says:
```
rm(list = ls()) # Clear the workspace!
ls() # No objects left in the workspace

A good way to start most R scripts
```
That is very inaccurate! That is a very bad way to start R scripts because it destroys the user's environment, which may hold important data (it gets worse when students use Shiny and do things like that, erasing the environment of the Shiny server).

Somewhere it should be clearly explained that students should never use `rm` and `setwd` in scripts without a very, very good reason. The users are aware of the environment and working directories and scripts should not try to outsmart the users.

**Comment by janverbesselt** [comment]
Agree! Bug fixed and extra info is added. Please check. See also the new issue for further enhancement.
