### ISSUE TITLE
adding Rmarkdown Rpubs as a pro tip

### ISSUE THREAD

**Issue by janverbesselt** [GeoScripting-WUR/Scripting4GeoIntro#6]
-> pro tip as a bonus to submit the Rpubs link to the solution for the assignment

**Comment by GreatEmerald** [comment]
We already have a bonus defined, though. So we'd either need to replace our current bonus (make it into a task - that may be a good idea, actually), or make publishing into a bonus for some other lesson.

**Comment by janverbesselt** [comment]
turning the current bonus into a task can potentially be to difficult for a lot of students. But I would agree turning the publishing option into a bonus.
